### PR TITLE
Implemented 5 minutes cache to face API rate limits

### PR DESCRIPTION
**Pull request by Slamdunk**
https://github.com/FernandoMiguel/sshremotekeys/issues/2

Script is tested against [ShellCheck v0.4.6](https://github.com/koalaman/shellcheck/releases/tag/v0.4.6) to provide maximum shell compatibility.

### CODE REVIEW

**Comment by FernandoMiguel** [comment]
I'm not comfortable with dropping AWS S3 bucket example (especially since that's the one I actively use).
I don't want to make people think this is GH only.

Can you please incorporate both examples in your code?

Cheers

**Comment by FernandoMiguel** [comment]
Nevermind last comment. 
just saw the commented bucket url.

it probably needs to have both comment and ask the dev to choose one and uncomment.

**Comment by Slamdunk** [comment]
I was focused on producing one version of a functioning code in order to avoid (error) duplication.

Feel free to merge and edit the code to make it more manual friendly: commenting both is a good idea, so the user must read/choose/think 😉

**Review by FernandoMiguel — APPROVED** [review]
Merged.
Will comment both URLs, and update Docs

**Pull request merged**
